### ISSUE TITLE
Version 5 PCB to-do list

### ISSUE THREAD

**Issue by HWXLR8** [HWXLR8/beef-board#44]
- [x]  Fix chip reset (https://github.com/HWXLR8/beef-board/issues/28)
- [x]  Reverse 4 pin encoder pin ordering (5ad248a44e940dccef677540d5273de8867dade5)
- [x]  Add jumper between BUS and AUX 5V (016214301a05c4844d6649bfeba64fc961c18a41)
- [x] Move pwan AUX 2-pin closer to 5-pin (7a32bb05fe54354f62b4c05a49bae48dec875169)
- [x] Add new slikscreen (044856f65555a47e1522f14873f55c4edff88f71)
- [x] Update BOM in README (114403c7b63636c8a7de8c8b4bd2b4dd8c75e62a)
- [x] Update PCB pics
- [x] Fix silkscreen to reflect missing B8 if necessary (N/A)
- [x] Add SDVX silkscreen (N/A)
- [x] Move 2N7002 transistors into clear view (4a06a141ca6fd4496f06b375f950cd44f228dda7)

**Comment by ASleepyCat** [comment]
Would it be possible to relocate the USB power headers closer to the edge of the board? I managed to damage the 2-pin power cable while trying to get it out since it was so taught.

**Comment by HWXLR8** [comment]
No problem, added to the list.
